# Generated by Django 4.2.2 on 2024-05-16 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50, unique=True)),
                ('valor_producto', models.IntegerField()),
                ('descripcion_producto', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Producto',
            fields=[
                ('id_tipoProducto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_producto', models.CharField(default='Sin tipo', max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_stock', models.IntegerField(default=0)),
                ('nombre_producto', models.ForeignKey(default='Sin Producto', on_delete=django.db.models.deletion.CASCADE, to='core.producto', to_field='nombre_producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(default='Sin tipo', on_delete=django.db.models.deletion.CASCADE, to='core.tipo_producto', to_field='tipo_producto'),
        ),
    ]
