# Generated by Django 5.0.6 on 2024-07-01 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('tipo_usuario', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion_producto',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('password_usuario', models.CharField(max_length=24)),
                ('pnombre', models.CharField(max_length=30)),
                ('snombre', models.CharField(blank=True, max_length=30, null=True)),
                ('apaterno', models.CharField(max_length=30)),
                ('amaterno', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.CharField(max_length=50)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('productos', models.CharField(max_length=300)),
                ('valor_total', models.IntegerField()),
                ('orden_compra', models.CharField(max_length=50)),
                ('codigo_auth', models.CharField(max_length=50)),
                ('fecha_transaccion', models.TimeField()),
                ('rut', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
